#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/db1
#  thymeleaf:
#    mode: HTML
#logging:
#  level:
#    root: info
#    com.lrm: debug
#  file:
#    name: log/blog-dev
#server:
#  port: 8081