spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.94.17.30:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  mvc:
    formcontent:
      putfilter:
        enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: utf-8
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      use-new-id-generator-mappings: false
#    show-sql: true
#    generate-ddl: true
logging:
  level:
    root: info
    com.lrm: debug
  file:
    name: log/blog-dev
mybatis:
  typeAliasesPackage: com.wsx.blog.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8888


